# Make a small summary of system information
# Print the result to the screen and write the information to a log file

#!/bin/bash

# Defining the variables needed for system information
freespace=$(df -h / | grep -E "\/$" | awk '{print $4}') # Available free space on the root volume 

# For formating strings
greentext="\033[32m"
bold="\033[1m"
normal="\033[0m"

logdate=$(date +"%Y%m%d") # Prints current date
logfile="$logdate"_report.log # Create log file by concatinating with date 

echo -e $bold"System Report for: "$greentext"$HOSTNAME"$normal # Formating the string
printf "\tSystem type:\t%s\n" $MACHTYPE
printf "\tBash Version:\t%s\n" $BASH_VERSION
printf "\tFree Space:\t%s\n" $freespace
printf "\tFiles in dir:\t%s\n" $(ls | wc -l) # List and count number of things in the directory
printf "\tGenerated on:\t%s\n" $(date +"%m/%d/%y") # Date formate
echo -e $greentext"A summary has been created to $logfile"$normal

# Take the outputs of the cat and put that into a log file
cat <<- EOF > $logfile
	This report was automatically generated by my Bash script.
	It contains a brief summary of some system information.
EOF

printf "SYS:\t%s\n" $MACHTYPE >> $logfile
printf "BASH:\t%s\n" $BASH_VERSION >> $logfile
